<?php

/**
 * Implements hook_commerce_order_status_info().
 */
function legiest_commerce_commerce_order_status_info() {
  $order_statuses = array();
  
  $order_statuses['processing_special'] = array(
    'name' => 'processing_special',
    'title' => t('Processing : Administration'),
    'state' => 'pending',
    'cart' => FALSE,
  );
  $order_statuses['pending_special'] = array(
    'name' => 'pending_special',
    'title' => t('Pending : Administration'),
    'state' => 'pending',
    'cart' => FALSE,
  );
  
  return $order_statuses;
}

/**
 * Implements hook_commerce_tax_rate_info().
 */
function legiest_commerce_commerce_tax_rate_info() {
  $tax_rates = array();

  $tax_rates['tva_standard'] = array(
    'title' => t('TVA standard'),
    'rate' => .196,
    'type' => 'vat',
    'default_rules_component' => FALSE,
    'admin_list' => TRUE,
  );

  return $tax_rates;
}

/**
 * Implements hook_permission().
 */
function legiest_commerce_permission() {
  return array(
    'use special order states' => array(
      'title' => t('Use special order states'),
      'description' => t('Allow the user to be delivered before paying (for administrations)'),
    ),
  );
}
